### ISSUE TITLE
clinical 

### ISSUE THREAD

**Issue by AMAwatermelon** [ayueme/easyTCGA#2]
首先感谢作者！我注意到临床信息不是很全，比如drug的信息在xml里有，但是包里整理的没有，有没有办法下载到全面的临床信息

**Comment by ayueme** [comment]
请给一个详细一点的，可复现的例子，包括代码

**Comment by ayueme** [comment]
> 首先感谢作者！我注意到临床信息不是很全，比如drug的信息在xml里有，但是包里整理的没有，有没有办法下载到全面的临床信息

已更新，单独增加一个专门下载XML临床临床信息的函数。
